package Enums;

public enum CAPTURE_ENCRYPT_TYPE {
    CAPTURE_ENCRYPT_TYPE_UNKNOWN,
    CAPTURE_ENCRYPT_TYPE_TDES,
    CAPTURE_ENCRYPT_TYPE_AES,
    CAPTURE_ENCRYPT_TYPE_NONE,
    CAPTURE_ENCRYPT_TRANS_ARMOUR;

    private CAPTURE_ENCRYPT_TYPE() {
    }
}
