package Enums;

public enum DEVICE_TYPE {
    IDT_DEVICE_UNKNOWN(0),
    IDT_DEVICE_AUGUSTA_HID(1),
    IDT_DEVICE_AUGUSTA_KB(2),
    IDT_DEVICE_AUGUSTA_S_HID(3),
    IDT_DEVICE_AUGUSTA_S_KB(4),
    IDT_DEVICE_AUGUSTA_S_TTK_HID(5),
    IDT_DEVICE_SPECTRUM_PRO(6),
    IDT_DEVICE_MINISMART_II(7),
    IDT_DEVICE_UNIPAY(8),
    IDT_DEVICE_UNIPAY_I_V(9),
    IDT_DEVICE_VP3300_AJ(10),
    IDT_DEVICE_L100(11),
    IDT_DEVICE_KIOSK_III(12),
    IDT_DEVICE_KIOSK_III_S(13),
    IDT_DEVICE_VENDI(14),
    IDT_DEVICE_VP3300_USB(15),
    IDT_DEVICE_UNIPAY_I_V_TTK(16),
    IDT_DEVICE_VP3300_BT(17),
    IDT_DEVICE_VP8800(18),
    IDT_DEVICE_NEO2(19),
    IDT_DEVICE_MINISMART_II_COM(IDT_DEVICE_NEO2.deviceType+5),
    IDT_DEVICE_SPECTRUM_PRO_COM(21),
    IDT_DEVICE_KIOSK_III_COM(22),
    IDT_DEVICE_KIOSK_III_S_COM(23),
    IDT_DEVICE_NEO2_COM(24),
    IDT_DEVICE_MAX_DEVICES(IDT_DEVICE_NEO2_COM.deviceType+5);

    private int deviceType;

    DEVICE_TYPE(int device){ this.deviceType = device; }

    public int getDeviceType(){ return deviceType; }
}
